### ISSUE TITLE
Mismatch in code and paper.

### ISSUE THREAD

**Issue by LalitPradhan** [david-klindt/NIPS2017#2]
In the paper you have mentioned:
We set this pixel to the standard deviation of the neuron’s response (because
the output of the convolutional layer has unit variance) and initialized the rest of the mask randomly
from a Gaussian N(0,0.001). We initialized the convolution kernels randomly from N(0,0.01) and the feature weights from N(1/K,0.01).

In the figure3 python notebook however:
init_scales = np.array([[0,.01],[0,.001],[1,.1]])#Mean/SD for Kernel,Mask,Weights
for K = 1.

There is a difference between the feature Weight inits mentioned in paper and code. Which is the correct one?

**Comment by david-klindt** [comment]
It should be as written in the paper. However, since this is the one-kernel example (so no feature selection needed) and any scaling can be done in the mask, the weighing-layer is actually not needed here. Practically, it would be easier to fix the weight to 1 or just remove it. It is only kept in here for coherence with the other models. Thanks for pointing out!

**Comment by LalitPradhan** [comment]
Thanks. It indeed shouldn't I think now since you mentioned.
