### ISSUE TITLE
Doubt in Dropouts

### ISSUE THREAD

**Issue by LalitPradhan** [david-klindt/NIPS2017#3]
What is the intuition for using dropout before every conv layer in fig3?
Also the dropout rate is set to reg[3] while reg is defined as reg = [0,.001,0]#regularization parameters: L2 Kernels, L1 Mask, L1 Weights
 Please clarify this. Thanks.

**Comment by aecker** [comment]
Can you specify which file name and line number you're talking about?

**Comment by david-klindt** [comment]
Thanks for the question! The drop-out came in later inspired by (McIntosh et al., 2016), but we never actually used! Which is why e.g. in fig5 you always find reg[3]=0. So it can be savely ignorred, either take it out from the TF model or, if you just want the code to run, append a 0 to the reg list. As with your previous question, the fig3 toy-model is really quite a bit simpler than what we used later, so the CNN.py module is not the most parsimonious way of coding it (more a feeble attempt at letting the different models share the same scripts).

**Comment by LalitPradhan** [comment]
Thanks.
